### PR TITLE
Added the pulling commands for the browsers and the videorecorders related #5

### PR DESCRIPTION
**Pull request by augustocristian**
Several executions were unstable due to issues with the videorecorder, and the images from the browsers were not available in the CI-agent. Since this is a crucial part of the setup, I have included the pulling command for the two images in the COI-setup script

### CODE REVIEW

**Comment by javiertuya** [comment]
@augustocristian Note that you are pulling Chrome 94, that is quite outdated

**Comment by augustocristian** [comment]
Image updated to 116.0 and tested during several executions in the branch

**Comment by javiertuya** [comment]
@augustocristian Again: Why are you running the main branch manually? The tests should be run in the feature branch. As in this case the goal is to check a flaky, run as many times as you need, but NOT in the main branch.

**Review by javiertuya — APPROVED** [review]
Note that one of the builds on main is unstable (164). It is still flaky, but less that before.
Update the branch with latest main before I can merge.

**Pull request merged**
